rails/config/routes.rb
Partypeeple::Application.routes.draw do

  get "reports/index"

  get "reports/gender"

  get "party/orientation"

  get "public/closed"
  
  match 'closed' => 'public#closed'

  match "party/index/(:letter)" => 'party#index', :as => :party

  match 'login' => 'public#login'

  match 'logout' => 'public#logout'

  match 'about' => 'party#about'
  
  match 'help' => 'party#help'
  
  match 'reset' => 'dashboard#reset'
  
  match 'dashboard/(:action)' => 'dashboard'
  
  match 'party/peep/(:identifier)' => 'party#peep'

  match 'party' => 'party#index', :as => :party

  match 'party/choose/(:choice)' => 'party#choose'

  match 'reports(/:action)' => 'reports'

  root :to => "public#index"
  

end

rails/app/views/layouts/application.html.erb
<!doctype html>
<html class="no-js" lang="en">
    <head>
        <title>Party Peeple</title>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
        <%= stylesheet_link_tag "screen" %>
        <script type="text/javascript" src="http://use.typekit.com/awr2bfm.js"></script>
        <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
        <%#= javascript_include_tag "jquery","script" %>
        <%= csrf_meta_tag %>
    </head>
    <body <%= "id=\"#{@body_id}\"".html_safe if @body_id %> <%= "class=\"#{@body_class}\"".html_safe if @body_class %>>
        <header>
            <h1>Party Peeple</h1>
        </header>
<%= yield(:nav) %>
<%= yield(:content) %>
        <footer>
            <p>Powered by e-Geaux, brought to you by <a href="http://pepysinc.com/">Pepys, Inc.</a></p>
        </footer>
        <script src="/javascripts/jquery.js" defer="defer"></script>
        <script src="/javascripts/script.js" defer="defer"></script>
    </body>
</html>

rails/app/views/layouts/dashboard.html.erb
<!doctype html>
<html class="no-js" lang="en">
    <head>
        <title>Party Peeple</title>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
        <link rel="stylesheet" href="http://twitter.github.com/bootstrap/1.3.0/bootstrap.min.css">
    </head>
    <body >
        <header>
            <% if authenticated? %>
            <%= link_to "Peeps", party_url %> | 
            <%= link_to "Reset Data!", reset_url %> 
            <% end %>
        </header>


        <%= yield %>

    </body>
</html>

rails/app/views/layouts/general.html.erb
<% content_for :nav do %>
  <% if authenticated? && params[:action] != "orientation" %>
        <nav>
            <ul>
                <li class="<%= tab_selector("index") %>"><%= link_to "Peeps", party_url %></li>
                <li class="<%= tab_selector("help") %>"><%= link_to "Help", help_url %></li>
                <li class="<%= tab_selector("about") %>"><%= link_to "About", about_url  %></li>
          <% if administrator? %>
                <!--li><%= link_to "Dashboard", :controller => :dashboard %></li-->
          <% end %>
            </ul>
        </nav>
  <% end %>
<% end %>
<% content_for :content do %>
<%= yield %>
<% end %>
<%= render :file => 'layouts/application' %>

rails/app/views/layouts/reports.html.erb
<html>
    <head>
        <title>Party Peeple</title>
        <meta charset="utf-8" />
        <meta http-equiv="refresh" content="15;url=/reports">
        <style>
            html, body, div, span, applet, object, iframe, h1, h2, h3, h4, h5, h6, p,
            blockquote, pre, a, abbr, acronym, address, big, cite, code, del, dfn, em, img,
            ins, kbd, q, s, samp, small, strike, strong, sub, sup, tt, var, b, u, i,
            center, dl, dt, dd, ol, ul, li, fieldset, form, label, legend, table, caption,
            tbody, tfoot, thead, tr, th, td, article, aside, canvas, details, embed,
            figure, figcaption, footer, header, hgroup, menu, nav, output, ruby, section,
            summary, time, mark, audio, video {
                margin: 0;
                padding: 0;
                border: 0;
                font-size: 100%;
                font: inherit;
                vertical-align: baseline;
            }
            body {
                line-height: 1;
                -webkit-text-size-adjust:none;
                -ms-text-size-adjust:none;
            }
            ol, ul {
                list-style: none;
            }
            blockquote, q {
                quotes: none;
            }
            blockquote:before, blockquote:after, q:before, q:after {
                content: '';
                content: none;
            }
            table {
                border-collapse: collapse;
                border-spacing: 0;
            }
            article, aside, details, figcaption, figure,
            footer, header, hgroup, menu, nav, section {
                display: block;
            }
            h1, h2, h3, h4, h5, h6{
                text-rendering: optimizeLegibility;
            }
            label, input[type="button"], input[type="submit"], input[type="image"], button{
                cursor: pointer;
            }
            input[type="text"], input[type="password"], input[type="submit"],
            input[type="email"], input[type="search"], input[type="tel"],
            input[type="url"], input[type="color"], button{
                -webkit-appearance: none;
                -moz-apperance: none;
            }
            input[type="radio"]{
                vertical-align: text-bottom;
            }
            input[type="checkbox"]{
                vertical-align: bottom;
            }
            .ie7 input[type="checkbox"]{
                vertical-align: baseline;
            }
            input, select{
                vertical-align: middle;
            }
            .ie6 input{
                vertical-align: text-bottom;
            }
            button{
                width: auto;
                overflow: visible;
            }
            button, input, select, textarea{
                margin: 0;
            }
            .ie6 textarea,
            .ie7 textarea{
                overflow: auto;
            }
            .ie6 legend,
            .ie7 legend{
                margin-left: -7px;
            }
            sub, sup{
                font-size: 75%;
                line-height: 0;
                position: relative;
            }
            sup{
                top: -0.5em;
            }
            sub{
                bottom: -0.25em;
            }
            .ie7 img{
                -ms-interpolation-mode: bicubic;
            }
            html{
                position: relative;
                height: 100%;
                width: 100%;
                background: #FFF;
            }
            body{
                width: 824px;
                height: 568px;
                position: absolute;
                top: 50%;
                left: 50%;
                margin-left: -512px;
                margin-top: -384px;
                padding: 100px;
            }
            h1{
                font: bold 48px 'Helvetica Neue', 'Helvetica', sans-serif;
                color: #333;
                margin-bottom: 75px;
            }
        </style>
    </head>
    <body>
        <%= yield %>
    </body>
</html>